### PR TITLE
Merge Fork Repository(fix and new featres)

### PR DESCRIPTION
**Pull request by kawa1214**
#19

Hi @lfariaUnifei
Thanks for the fixes and added features.

I would like to merge your branches.
Please let me know if you have any concerns.

### CODE REVIEW

**Comment by llfaria** [comment]
Oh, that was unexpected, i would be happy if you merge, only notice the need of change dependencies in  tools/analyzer_plugin
[cid:93ef78cc-4a27-4b5b-8a82-d3de9c235cf1]
________________________________
De: Ryo Kawamura ***@***.***>
Enviado: sexta-feira, 25 de novembro de 2022 14:25
Para: kawa1214/import-lint ***@***.***>
Cc: Luã Oliveira de Faria ***@***.***>; Mention ***@***.***>
Assunto: [kawa1214/import-lint] Merge Fork Repository (PR #20)


#19<https://github.com/kawa1214/import-lint/issues/19>

Hi @lfariaUnifei<https://github.com/lfariaUnifei>
Thanks for the fixes and added features.

I would like to merge your branches.
Please let me know if you have any concerns.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/kawa1214/import-lint/pull/20

Commit Summary

  *   aa6acbb<https://github.com/kawa1214/import-lint/pull/20/commits/aa6acbb79d1f1e7203fd570ff2c801d8422dad17> fix: separator on windows by using platform separator
  *   8182cb9<https://github.com/kawa1214/import-lint/pull/20/commits/8182cb96f3e323377608383104f43bc7994f8c37> fix: imports normalized
  *   ad6d0f2<https://github.com/kawa1214/import-lint/pull/20/commits/ad6d0f2a6edcd09dd73ddfcce1a4213a320036f7> feature: ignore files
  *   43b35c3<https://github.com/kawa1214/import-lint/pull/20/commits/43b35c343c1ab01119bdf069c54339382f2cceb1> feture: including test in path normalization
  *   88d8bf4<https://github.com/kawa1214/import-lint/pull/20/commits/88d8bf430912379eeda3568db3c1ee53700eccee> fix: group of rule
  *   9c5b991<https://github.com/kawa1214/import-lint/pull/20/commits/9c5b991b431cfd592164c39057432adcbe8577ee> fix: include test
  *   127e06d<https://github.com/kawa1214/import-lint/pull/20/commits/127e06d5de8bfbb79eadb1dfb11a94240d13a644> test
  *   706e279<https://github.com/kawa1214/import-lint/pull/20/commits/706e27901febbdbc5d326978f8371a0c3c82d5f2> test
  *   4ac1608<https://github.com/kawa1214/import-lint/pull/20/commits/4ac16083dadb77947340ec2fbddb63479f0c4a90> fix: plugin
  *   0e522d2<https://github.com/kawa1214/import-lint/pull/20/commits/0e522d22bc92552d68fc19264e65f199d876d64c> fix
  *   2fd0a98<https://github.com/kawa1214/import-lint/pull/20/commits/2fd0a984bf5b481b14090e848d6ee31f4bfc4bfa> fix: import plugin
  *   ba088e4<https://github.com/kawa1214/import-lint/pull/20/commits/ba088e48761d48a820bb7cf6ab6dbefb150d955b> chore: idea stuff
  *   fd98a2a<https://github.com/kawa1214/import-lint/pull/20/commits/fd98a2ad6c5a64c70ff39308859bbf97f01a717a> ignore
  *   cc8f0b4<https://github.com/kawa1214/import-lint/pull/20/commits/cc8f0b411bfd681f325517dbf0c9cd5a55ce0ede> fix: tools
  *   c53ef2a<https://github.com/kawa1214/import-lint/pull/20/commits/c53ef2aafed474ba3ccd983dcc29867e650316bf> fix: example
  *   e7233af<https://github.com/kawa1214/import-lint/pull/20/commits/e7233afe416996d196be5888681950a74b5902ba> fix: included path
  *   c4dca54<https://github.com/kawa1214/import-lint/pull/20/commits/c4dca54ff4a70aa2c530b95d75c79ab29ff2c486> fix: clear errors
  *   c6d5059<https://github.com/kawa1214/import-lint/pull/20/commits/c6d505950f3393b262d4d3ba665769ac6e9ac24b> test
  *   57853da<https://github.com/kawa1214/import-lint/pull/20/commits/57853dad9320171f383f19f0957dc50569c5b086> test
  *   e14b94d<https://github.com/kawa1214/import-lint/pull/20/commits/e14b94dbb337fbed6f16a4d419a1553bb858f83c> test
  *   5383290<https://github.com/kawa1214/import-lint/pull/20/commits/5383290782574e25ce0e747430b9dd8217f84491> test
  *   9c55519<https://github.com/kawa1214/import-lint/pull/20/commits/9c555191e9ef643927e86b2e12a565fc79c4b001> test
  *   d81176e<https://github.com/kawa1214/import-lint/pull/20/commits/d81176e48b9fb9b3353acc3069143e6a129680fa> test
  *   8686989<https://github.com/kawa1214/import-lint/pull/20/commits/8686989c4401437b252ecc994e88a7649e1d65d9> removed logs
  *   c8e872a<https://github.com/kawa1214/import-lint/pull/20/commits/c8e872a0b5506e0fb26a0697402a04144fc73f9c> chore: gitignore
  *   a2383c0<https://github.com/kawa1214/import-lint/pull/20/commits/a2383c029c4390a015b719dbabaf20dacc9630b8> refactor: better organization
  *   3685de7<https://github.com/kawa1214/import-lint/pull/20/commits/3685de7bec3f44eb5f590ae824e0ae429ce98afc> feature: support package
  *   70622eb<https://github.com/kawa1214/import-lint/pull/20/commits/70622eba34fc7240b87107a0ca3193588aa8e254> feature: allow package rule
  *   200c40b<https://github.com/kawa1214/import-lint/pull/20/commits/200c40b486a36fbb295516702a82b0a7db3e5c8d> fix: constraints for local relative import
  *   97a7c48<https://github.com/kawa1214/import-lint/pull/20/commits/97a7c485d0a57a56859dbd8f7374a39c7e65344f> fix: param name
  *   548dbb8<https://github.com/kawa1214/import-lint/pull/20/commits/548dbb883c17d347a9ab2421584bfabec8b99da8> chore: update analyzer

File Changes

(58 files<https://github.com/kawa1214/import-lint/pull/20/files>)

  *   M .gitignore<https://github.com/kawa1214/import-lint/pull/20/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (2)
  *   A .idea/.gitignore<https://github.com/kawa1214/import-lint/pull/20/files#diff-21610973868a98feff98dd0460438a8a32cca1447bc8701537ec5048e0c5faeb> (8)
  *   A .idea/import-lint.iml<https://github.com/kawa1214/import-lint/pull/20/files#diff-f64f26dd3ae2a6efbe3068f80535930132eb515c95dc3f33be524fb6b595a9ca> (21)
  *   A .idea/libraries/Dart_Packages.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-0c613c5e1c2d088e65d7f66175b96a419a2814c6beb1479b13e9503b69b41f63> (476)
  *   A .idea/libraries/Dart_SDK.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-cd395502c138d486f72fed5c896b3530d92ce54d2549492651e3f4338b212c12> (27)
  *   A .idea/misc.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-7ea1cd7bd5d16299a0abd33128e8d0a8bc04146f6b00c07bcd3cc0aad813c229> (6)
  *   A .idea/modules.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-0aae258f1732eac2acd4fcdd1af6d0737b4ec8d233136c3ba7c40b6d49aeda50> (8)
  *   A .idea/vcs.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-a6dab70bd0e9ffc91d8419ad52225baff3a3e7c9d8e1724f7ed6d96b661d804a> (6)
  *   M README.md<https://github.com/kawa1214/import-lint/pull/20/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5> (28)
  *   M bin/import_lint.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-4074bf1ea01ed4d4ed27e9acbfb4b09902a28ed79b10e0ccd302044bcded1932> (2)
  *   A example/.idea/.gitignore<https://github.com/kawa1214/import-lint/pull/20/files#diff-a1e5dec33cd011b6f04e608b9ac61ef33114bfe5c42830eaea3339657b0bbed8> (8)
  *   A example/.idea/example.iml<https://github.com/kawa1214/import-lint/pull/20/files#diff-8542921fea079d023e831ce9d90429b1251610dd001fe20432794196b8870e06> (15)
  *   A example/.idea/libraries/Dart_Packages.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-f2151765cf8b5792939f3c34ec8a7f2992b930e2e76fc266075ba850622c4387> (252)
  *   A example/.idea/libraries/Dart_SDK.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-1c3cbc25238933afdcbf1b10ba0e4f800f83a313baa1a636938f2846b9a28101> (27)
  *   A example/.idea/misc.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-ec27a356b9e152b5bf5e6d36f68386e93f4fec542b31cb63f3c40ee95425946d> (6)
  *   A example/.idea/modules.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-03a3e50810abea021057e791e9f5f3554a0d64a098c879d47adf1abf2e1013cc> (8)
  *   A example/.idea/vcs.xml<https://github.com/kawa1214/import-lint/pull/20/files#diff-4e3c1a51c31d25fb33a3302ef0beb1607c1a9b4385c057ba7d28b5fe25525b0e> (6)
  *   M example/analysis_options.yaml<https://github.com/kawa1214/import-lint/pull/20/files#diff-ef52b1226c697a95c613aacbd255ab4655f91a7d19c31fde92171b5c42e96771> (8)
  *   A example/lib/main.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15> (5)
  *   M example/lib/repository/sub/two/test_two_sub.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-527f502d64e2fa8647342bf668c9a33a06c1a2ce008bd16ac947243dce218aee> (1)
  *   M example/lib/space test/test.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-6f2111f7a14b8752abed75778bd2f3aa7d5e7a56dd8fd43b9c79b8103670a06a> (1)
  *   M example/lib/space test/testa.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-17f7ea222d4996790fb1f46961d050b03a398176941dfc01e460f15153fa625c> (1)
  *   M example/lib/use_case/base_use_case.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-3fee40a0d0d5adc551aaa4e672b53ee941bfe64aadef4b305634d2b938d68467> (16)
  *   M example/lib/use_case/test_one_use_case.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-49f9900b6d00d075bc71f51ae25b3ecc6ac4cc848d491aebc8d232e8c0d00f56> (4)
  *   A example/lib/use_case/test_three_use_case.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-6d00353850429da1c43bfb419c2d03baad83dd18113a4db38e927c0f74d5f938> (6)
  *   M example/pubspec.lock<https://github.com/kawa1214/import-lint/pull/20/files#diff-56034400269eedfae0a2f9ed76b72f7a6deb3a4806063c0c52edeac057376c5a> (89)
  *   M example/pubspec.yaml<https://github.com/kawa1214/import-lint/pull/20/files#diff-565b0869896732da3b937c64bc8fd5f0ca37ea1f629d579c29fc70e0f1e3e48e> (1)
  *   M lib/import_lint.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-19f86eb4ed242fbc402a8714e1d4db1913cd7d56b3884f048c81295792850643> (6)
  *   M lib/plugin/plugin.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-7ca209f0a7c85df90e8233db00f09835ff94c757f2c878fb5e0d6d0be2da0b1a> (177)
  *   A lib/src/application/import_lint_visitor.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-f0f9ef6d1b70e43d415b596f428d3e957893145bbbc7174f478839eb74856576> (76)
  *   A lib/src/domain/import.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-e086ce8b8bc793478b453174edc06aeda97894a005d168f5cb4dcce7894bf8e5> (43)
  *   A lib/src/domain/import_constraint.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-06e512f5f6ec8b616f219ad95d7d10772c6014517c639d3e1410b3d5a01a3e0d> (26)
  *   A lib/src/domain/rule_container.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-7d1bfae7508935877962658996d2ad94063426f23c3979a850b1d027830df2a2> (28)
  *   A lib/src/domain/rules/import-allowed.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-791594f31b32cf7f832d234c9e011ce8e9ede500564c1a5dd08cc63b63d7e01f> (21)
  *   A lib/src/domain/rules/rule.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-5bde766e4eb668e1526a1c14b9d8308ac00d9eb8f906744065160e2ea12ea5ae> (9)
  *   A lib/src/domain/rules/source-file-included.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-b2fb1504d63bd3cdeb38e9fe02a3f43d77fe51474559b2c3bccc46479b94913f> (20)
  *   A lib/src/infra/analysis_options_reader.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-44a7da5f03811d3fed6b1c790038e63589754ce3bac4af6bdb84faf71e10d6cf> (45)
  *   R lib/src/infra/cli.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-fef46ed174f39eee73fc6e21f052df154f6af4a94328346e37552053f821e6d7> (8)
  *   A lib/src/infra/error_collector.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-0eedf67ceb2979b9e7ab61aea63c4a0c22055ea31dfb22f5dea89326b0a2377b> (43)
  *   R lib/src/infra/exceptions.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-734d5d6f8ff20806121bfe4e5ad4f9d68c278c1af40df134a033ab9d01058257> (0)
  *   A lib/src/infra/factory/rule-container-factory.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-150595a3a6868b89870cde76c7e39fd42c7b99fe54625968447e06af8e1d3b80> (40)
  *   A lib/src/infra/factory/rule-factory.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-cb06158883aa4ca81951d2729be3497748dfc069aa1da721f7a2bf7f10c42f32> (58)
  *   D lib/src/lint_options.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-19a97473720b49f9875eb4e4539391e2a5133bc44961261e01f5f92b3e28fa9f> (164)
  *   A lib/src/main/create_container_factory.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-f9e0a19de318b32b3dc79ca5369d91a762431656385cb25de8810c07c815aaa9> (10)
  *   A lib/src/main/create_error_collector.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-8a54c5d81cde61a249625c3657cb18887cb5c6c0e923cc6c403725333cd9f8b3> (9)
  *   D lib/src/rule.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-0be5c0bb8d01042962e60e05ed39f71830c1c75bbd712ce2a14143da8c75ed49> (182)
  *   M lib/src/utils.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-17db63ed2e34bd40b2bf89c04f997ba760e4fd75b04e6cf03f58349bd458477d> (28)
  *   M pubspec.lock<https://github.com/kawa1214/import-lint/pull/20/files#diff-e125d55a387d4b24048735f9ca6508c4e860f5ca1f3242edfd9df27e7d8a7af0> (54)
  *   M pubspec.yaml<https://github.com/kawa1214/import-lint/pull/20/files#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25> (14)
  *   M test/helper/coverage_test.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-8e6f2f08626e76370c470e7f83140355768be4ed2c3220fb2aa91c8523448767> (9)
  *   M test/lint_options.test.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-b309aa0094f9bbd58735cdfc5744bb60e49132e88ab64de1c78ebea8d2cdd5e8> (3)
  *   M test/rule.test.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-91fb88ecd47496098bab47b0d302e021ee18676eae024affec4d6a6b75df9878> (1)
  *   D tool/helper/dart_coverage_helper.sh<https://github.com/kawa1214/import-lint/pull/20/files#diff-0d246e17bde514eabd949f511a072a95a48b2e1fccfa154301fa98485e744bcf> (16)
  *   D tool/test.sh<https://github.com/kawa1214/import-lint/pull/20/files#diff-3c59f6df95cb9632a5c6331e1904344d39a0030ec44b9ea35a693e7ab41463bc> (17)
  *   A tool/uncovered_coverage.dart<https://github.com/kawa1214/import-lint/pull/20/files#diff-44c4cf835c0c86d9f31e6137686bb1297767f5c5725e34daa978a331d9b16610> (75)
  *   A tools/analyzer_plugin/analysis_options.yaml<https://github.com/kawa1214/import-lint/pull/20/files#diff-0ece68feb1099d011c7fe94ac2ad16b474f634af5f6dfb456b2824a36a76ed04> (0)
  *   D tools/analyzer_plugin/pubspec.lock<https://github.com/kawa1214/import-lint/pull/20/files#diff-aa369fa832af08250b717a961153014210186956e029a95b657e41f8393a0935> (173)
  *   M tools/analyzer_plugin/pubspec.yaml<https://github.com/kawa1214/import-lint/pull/20/files#diff-7afa4a9ab8509b7e8001c2394a9ed84db94698bee93f9e6f6e991453415502ec> (8)

Patch Links:

  *   https://github.com/kawa1214/import-lint/pull/20.patch
  *   https://github.com/kawa1214/import-lint/pull/20.diff

**Comment by kawa1214** [comment]
@lfariaUnifei 
Thanks for letting me know!

I want to merge nice changes.
May I ask you to create a pull request on the kawa1214:feat/merge-forked-repo-lfariaUnifei branch?

It is okay even if you are experiencing errors.

**Comment by llfaria** [comment]
Still need me to create a pull request?

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kawa1214** [comment]
@lfariaUnifei 
Thanks for the reply.Sorry, I deleted my comment.
Thanks, but no thanks.I created a pull request from the commit as of the forked main branch.

**Pull request merged**
